version: '3'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laundromat
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
